### ISSUE TITLE
npm install Error

### ISSUE THREAD

**Issue by lk125454242** [antoniandre/splitpanes#77] opened 2020-01-22 03:03 UTC
`npm i --S splitpanes@^2`

Only these three files
`LICENSE 
package.json
README.md
`
No folders src or dist

**Comment by antoniandre** [comment] 2020-01-22 04:32
Hi @lk125454242,

There was probably a problem when you tried to install.
`npm i --S splitpanes@^2` should work just fine as well as `npm i --S splitpanes`.

I just double-checked a fresh install and there is a `dist` folder in node_modules > splitpanes.

Also works in Codesandebox or Codepen:
https://codesandbox.io/s/vigorous-silence-wivh0?fontsize=14&theme=dark

**Comment by antoniandre** [comment] 2020-01-27 23:02
Hi @lk125454242, I hope the issue is fixed on your end. 
I am closing the issue as I have no news, please reopen if still not solved, with steps to reproduce and if you can a reproduction link. 
Cheers.

**Closed by antoniandre** 2020-01-27 23:02 UTC
