### ISSUE TITLE
Collapsible Panes

### ISSUE THREAD

**Issue by zihniogmen** [antoniandre/splitpanes#100] opened 2020-09-15 13:07 UTC
This is a cool library.

But few things are missing in terms of UX.

1. It would be nice to have a collapsible pane behaviour. (i.e https://codepen.io/rubenvincenten/pen/rzXvBy)
2. When double clicking on the separator, pane will expand to its full size. This is nice.. But it doesn't work for first pane. It should also work for first pane.

**Comment by antoniandre** [comment] 2020-09-22 13:49
Thanks for the feedback @zihniogmen,

The Codepen does not seem to load because of the http://lorempixel.com website that doesn't load neither.

> When double clicking on the separator, pane will expand to its full size. This is nice.. But it doesn't work for first pane. It should also work for first pane.

This is possible here: https://antoniandre.github.io/splitpanes/#change-direction
(`first-splitter` option)

**Comment by zihniogmen** [comment] 2020-09-22 21:35
Thank you for the response @antoniandre 

first-splitter option is working fine.

Here is the new Codepen example that points to the other feature;

https://codepen.io/zihniogmen/pen/vYGvJOz

**Comment by antoniandre** [comment] 2020-11-17 00:15
Hi @zihniogmen, sorry for the delay.
- First splitter is already an option
- Regarding your suggestion on the Codepen, thanks for the reproduction link.
  A double click on the splitter already maximizes the pane and this is the most intuitive expected behavior.
  If you want to maximize the pane only on 1 side as you show in your demo, this is possible via the emitted events, just adjust the panes sizes externally: for instance, instead of 33% - 33% - 33%, on splitter click you can set them to 0% - 66% - 33%.
  Since this is possible and not a common use I let you add the custom behavior in your code and I am closing the issue. But thanks for your feedback! ;)

**Closed by antoniandre** 2020-11-17 00:15 UTC
